# Player data autosave time - in minutes, 0 to disable (NOT RECOMMENDED, WILL LOSE DATA ON SERVER CRASH!)
player-auto-save: 17
# Helper data autosave time - in minutes, 0 to disable (NOT RECOMMENDED!)
helper-auto-save: 15
# World/Islands data autosave time - in minutes, 0 to disable (NOT RECOMMENDED!)
world-auto-save: 11

# Caution should be exercised when modifying the world generator options
world-generator: "CleanroomGenerator:."

# Definitions for worlds managed by this plugin. For Gui worlds seen by players see the gui-screens
# section below.
world-settings:
  normal:
    bukkit-name: "islands-normal"
    # Sizes are in chunks
    island-size: 12
    border-size: 2
    y: 128
    starting-biome: PLAINS
    allow-party: true
    allow-helpers: true
    # Automatic allocator settings
    islands-per-row: 100
  challenge:
    bukkit-name: "islands-challenge"
    # Sizes are in chunks
    island-size: 12
    border-size: 2
    y: 128
    starting-biome: TAIGA
    allow-party: true
    allow-helpers: true
    islands-per-row: 100
  hardcore:
    bukkit-name: "islands-hardcore"
    # Sizes are in chunks
    island-size: 12
    border-size: 2
    y: 128
    starting-biome: HELL
    allow-party: false
    allow-helpers: true
    islands-per-row: 100

# Settings for the WorldEdit API
worldedit-api:
  # Leave this to true for increased island creation speed and support for larger islands
  ignore-air-blocks: true
  # This must be true if you have entities (e.g. animals) saved in your schematic and you want these restored.
  paste-entities: true

# Schematic definitions. These are grouped by world type. The actual schematic node name (schematic1,
# schematic2, etc.) doesn't matter as long as it's unique for a given world type.
#
# Name and lores support Bukkit color codes.
#
# name - The name that is shown in the GUI
# title - The lore that's displayed in the GUI to players that have the permission to use it
# noperm-lore - The lore that's displayed in the GUI to players that do NOT have the permission to use it
# file - The file name where this schematic is stored in schematics/ folder
# permission - Permission node players must have to be able to use this schematic
#
schematics:
  normal:
    schematic1:
      file: "starter.schematic"
      # Block type that will be searched for in schematic and when found will be replaced by air and the island spawn set at that location.
      home-block: BEDROCK
      title: "&aClassic"
      icon: GRASS
      durability: 0
      permission: "emberisles.schematic.normal.default"
      lore:
      - "&aThis is the classic skyblock"
      - "&awith a tree and some basic"
      - "&aitems in a chest."
      noperm-lore:
      - "&cTo get access to this schematic"
      - "&cvisit our website at:"
      - "&9http://www.embercraft.us"
    schematic2:
      file: "donator1.schematic"
      home-block: BEDROCK
      title: "&6Big island"
      icon: DIAMOND_BLOCK
      durability: 0
      permission: "emberisles.schematic.normal.donator1"
      lore:
      - "&6Donator only skyblock"
      - "&aBigger island, more"
      - "&aresources than classic."
      noperm-lore:
      - "&cBuy access to this schematic"
      - "&cin our shop at:"
      - "&9http://shop.embercraft.us"
  challenge:
    schematic1:
      file: "starter.schematic"
      home-block: BEDROCK
      title: "&aClassic"
      icon: GRASS
      durability: 0
      permission: "emberisles.schematic.challenge.default"
      lore:
      - "&aThis is the classic skyblock"
      - "&awith a tree and some basic"
      - "&aitems in a chest."
      noperm-lore:
      - "&cTo get access to this schematic"
      - "&cvisit our website at:"
      - "&9http://www.embercraft.us"
  hardcore:
    schematic1:
      file: "starter.schematic"
      home-block: BEDROCK
      title: "&aClassic"
      icon: GRASS
      durability: 0
      permission: "emberisles.schematic.hardcore.default"
      lore:
      - "&aThis is the classic skyblock"
      - "&awith a tree and some basic"
      - "&aitems in a chest."
      noperm-lore:
      - "&cTo get access to this schematic"
      - "&cvisit our website at:"
      - "&9http://www.embercraft.us"

party-settings:
  # Invite expire times are in SECONDS
  member-invite-expire: 60
  helper-invite-expire: 60
  # Helper default duration if none is specified when players add a helper. This is in MINUTES
  helper-default-duration: 60
  ranks:
    default-rank:
      permission: "emberisles.use"
      party-limit: 5
    samplerank1:
      permission: "emberisles.party.donator1"
      party-limit: 10
    samplerank2:
      permission: "emberisles.party.donator2"
      party-limit: 15

island-protection-defaults:
  members:
    friendly-mobs: true
    hostile-mobs: true
    interact-doors: true
    interact-switches: true
    open-containers: false
    interact-anvils: true
    ride: true
    pick-ground-items: true
  helpers:
    friendly-mobs: false
    hostile-mobs: true
    interact-doors: true
    interact-switches: true
    open-containers: false
    interact-anvils: true
    ride: false
    pick-ground-items: true
  public:
    friendly-mobs: false
    hostile-mobs: false
    interact-doors: false
    interact-switches: false
    open-containers: false
    interact-anvils: false
    ride: false
    pick-ground-items: false

#
# Various virtual chest based Gui screens
#
# Most settings can be customized except gui config keys (e.g. world-selector).
# items: keys for items represent the slot number in the gui. First slot is 0.
#
# All settings in this section that can be customized apply instantly at runtime
# on /islandev reload
#
gui-screens:
  world-selector:
    inventory-rows: 1
    title: "&1Select your &6world type"
    items:
      '3':
        icon: STAINED_CLAY
        durability: 13            # green
        title: '&2Normal World'
        lore:
        - '&aIsland size: &696 x 96 blocks'
        - '&aDefault biome: &6PLAINS'
        - '&aParty allowed: &6yes'
        noperm-lore:
        - "&cTo get access to this world type"
        - "&cvisit our website at:"
        - "&9http://www.embercraft.us"
        permission: "emberisles.world.normal"
        world-type: "normal"
      '4':
        icon: STAINED_CLAY
        durability: 1            # orange
        title: '&2Challenge World'
        lore:
        - '&aIsland size: &696 x 96 blocks'
        - '&aDefault biome: &6TAIGA'
        - '&aParty allowed: &6no'
        - '&aSpecial rules: &6harder leveling'
        noperm-lore:
        - "&cTo get access to this world type"
        - "&cvisit our website at:"
        - "&9http://www.embercraft.us"
        permission: "emberisles.world.challenge"
        world-type: "challenge"
      '5':
        icon: STAINED_CLAY
        durability: 14           # red
        title: '&2Hardcore World'
        lore:
        - '&aIsland size: &696 x 96 blocks'
        - '&aDefault biome: &6HELL'
        - '&aParty allowed: &6no'
        - '&aSpecial rules: &6island lost on death'
        noperm-lore:
        - "&cTo get access to this world type"
        - "&cvisit our website at:"
        - "&9http://www.embercraft.us"
        permission: "emberisles.world.hardcore"
        world-type: "hardcore"
  schematic-selector:
    # increase inventory-rows if you have more than 9 schematics for a world type
    inventory-rows: 1
    title: "&1Select &6island schematic"
    # items are populated at runtime based on definitions above in schematics section
messages:
  print-loc: '&6Your current location is: &f%s'
  error-already-island: "&cYou can't own or be member on more than one island of the same type."
  error-no-free-islands: "&cCurrently there are no more free islands available in world %s. Inform an admin about this."
  error-not-from-console: "&cYou can't run this command from console."
  error-internal-misconfigured: "&cPlugin is misconfigured. Inform an administrator about this."
  error-schematic-format: "&cSchematic is in wrong format. Try using a different schematic and inform an admin about this."
  error-schematic-nospawn: "&cCould not find a suitable spawn point for your island. Ask an admin to set one for you."
  island-created: "&2Your island was created and you have been teleported to it."
  error-invalid-world-type: "&cInvalid world type %s. Allowed types are normal, challenge, hardcore."
  error-player-not-found: "&cCan't find specified player name."
  error-not-island-owner: "&cYou don't own an island."
  error-already-member: "&c%s is already a member on your island."
  error-already-pending: "&c%s already has a pending invite from you. You must wait before sending another invite to the same player."
  error-has-another-island: "&c%s is already part of another island team."
  error-you-another-island: "&cYou are already part of another island."
  error-party-limit: "&cYour party is at maximum member count. You have to remove someone first before you can add more players."
  error-world-noparty: "&cThis world doesn't allow parties."
  member-invite-sent-recipient: "&aYou have received an invite to join %s island. To accept the invite do &6/island accept %s&a. The invite will expire in %d seconds."
  member-invite-sent-sender: "&aMember invite sent to %s. It will expire in %d seconds."
  error-player-not-online: "&c%s is not online right now."
  error-not-member: "&c%s is not a member on your island."
  member-remove-sender: "&2You have removed %s from your island."
  member-remove-recipient: "&a%s has removed you from their island."
  island-member-help: "&cUsage: /island member <add | remove> <normal | challenge | hardcore> <player name>"
  error-no-invite: "&cYou don't have an invite from %s or it has already expired."
  error-invalid-invite: "&cThis invite is no longer valid and cannot be accepted."
  member-add-sender: "&2%s has accepted your invite and is now a member of your island."
  member-add-recipient: "&2You are now added to %s island."
  error-no-island: "&cYou don't have an island in the %s world."
  teleported-home: "&2You have been teleported to the island spawn."
  error-already-helper: "&c%s is already a helper on your island."
  island-helper-help: "&cUsage: /island helper <add | remove> <normal | challenge | hardcore> <player name> [add duration in minutes]"
  error-not-helper: "&c%s is not a helper on your island."
  helper-remove-sender: "&2You have removed %s as helper from your island."
  helper-remove-recipient: "&a%s has removed you as helper from their island."
  helper-invite-sent-recipient: "&aYou have received an invite to join as helper on %s island for %d minutes. To accept the invite do &6/island accept %s&a. The invite will expire in %d seconds."
  helper-invite-sent-sender: "&aHelper invite sent to %s. It will expire in %d seconds."
  error-already-helper-recipient: "&cYou were already a helper on %s island."
  helper-add-sender: "&2%s has accepted your invite and is now a helper on your island."
  helper-add-recipient: "&2You are now added as helper to %s island."
