# Player data autosave time - in minutes, 0 to disable (NOT RECOMMENDED, WILL LOSE DATA ON SERVER CRASH!)
player-auto-save: 17
# World/Islands data autosave time - in minutes, 0 to disable (NOT RECOMMENDED, WILL LOSE DATA ON SERVER CRASH!)
world-auto-save: 11

# Caution should be exercised when modifying the world generator options
world-generator: "CleanroomGenerator:."

world-settings:
  normal:
    bukkit-name: "islands-normal"
    # Sizes are in chunks
    island-size: 12
    border-size: 2
    y: 128
    starting-biome: PLAINS
    allow-party: true
  challenge:
    bukkit-name: "islands-challenge"
    # Sizes are in chunks
    island-size: 12
    border-size: 2
    y: 128
    starting-biome: TAIGA
    allow-party: false
  hardcore:
    bukkit-name: "islands-hardcore"
    # Sizes are in chunks
    island-size: 12
    border-size: 2
    y: 128
    starting-biome: HELL
    allow-party: false

#
# Schematic definitions. These are grouped by world type. The actual schematic node name (schematic1,
# schematic2, etc.) doesn't matter as long as it's unique for a given world type.
#
# Name and lores support Bukkit color codes.
#
# name - The name that is shown in the GUI
# lore - The lore that's displayed in the GUI to players that have the permission to use it
# noperm-lore - The lore that's displayed in the GUI to players that do NOT have the permission to use it
# file - The file name where this schematic is stored in schematics/ folder
# permission - Permission node players must have to be able to use this schematic
#
schematics:
  normal:
    schematic1:
      file: "starter.schematic"
      name: "&aClassic"
      permission: "emberisles.schematic.normal.default"
      lore:
      - "&aThis is the classic skyblock"
      - "&awith a tree and some basic"
      - "&aitems in a chest."
      noperm-lore:
      - "&cTo get access to this schematic"
      - "&cvisit our website at:"
      - "&9http://www.embercraft.us"
    schematic2:
      file: "donator1.schematic"
      name: "Big island"
      permission: "emberisles.schematic.normal.donator1"
  challenge:
    schematic1:
      file: "starter.schematic"
      name: "Classic"
      permission: "emberisles.schematic.challenge.default"
  hardcore:
    schematic1:
      file: "starter.schematic"
      name: "Classic"
      permission: "emberisles.schematic.hardcore.default"

island-protection-defaults:
  members:
    friendly-mobs: true
    hostile-mobs: true
    interact-doors: true
    interact-switches: true
    open-containers: false
    interact-anvils: true
    ride: true
    pick-ground-items: true
  helpers:
    friendly-mobs: false
    hostile-mobs: true
    interact-doors: true
    interact-switches: true
    open-containers: false
    interact-anvils: true
    ride: false
    pick-ground-items: true
  public:
    friendly-mobs: false
    hostile-mobs: false
    interact-doors: false
    interact-switches: false
    open-containers: false
    interact-anvils: false
    ride: false
    pick-ground-items: false

messages:
  print-loc: '&6Your current location is: &f%s'
